sudo: required
dist: trusty

language: go

go:
  1.8.1

services:
  mysql

before_install:
  ./travis-install.sh

install:
  go build server.go main_page.go register.go authorize.go sessions.go

script:
  go test server_test.go